feat: header
Etimo/diamonds2 pull request #267
Opened 2023-02-16 15:05 UTC by hejsaga

2023-02-16 15:13 UTC, H4zze approved these changes

2023-02-16 15:13 UTC, H4zze commented on frontend-typescript/index.html
> +    <link rel="icon" type="image/svg+xml" href="./src//assets//diamond.svg" />
dubbla `/`

2023-02-16 15:13 UTC, H4zze requested changes

2023-02-16 15:13 UTC, H4zze commented on frontend-typescript/index.html
> +    <link rel="icon" type="image/svg+xml" href="./src//assets//diamond.svg" />
this (råkade välja fel)

2023-02-16 15:15 UTC, hejsaga commented on frontend-typescript/index.html
> +    <link rel="icon" type="image/svg+xml" href="./src//assets//diamond.svg" />
💎

2023-02-17 08:36 UTC, H4zze approved these changes

2023-02-17 08:36 UTC, merged